---
# .github/release.yml

changelog:
  exclude:
    labels:
      - documentation
      - duplicate
      - invalid
      - question
      - wontfix
    authors:
      - super-linter[bot]
  categories:
    - title: Bug Fixes
      labels:
        - bug
    - title: Enhancements
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
